vich_uploader:
    db_driver: orm

    mappings:
        themes_images:
            uri_prefix: '%themes_images_directory%'
            upload_destination: '%kernel.project_dir%/public/img/upload/themes'
            namer: vich_uploader.namer_uniqid
            inject_on_load: true
        workshops_images:
            uri_prefix: '%workshops_images_directory%'
            upload_destination: '%kernel.project_dir%/public/img/upload/workshops'
            namer: vich_uploader.namer_uniqid
            inject_on_load: true
        workshops_documents:
            uri_prefix: '%workshops_documents_directory%'
            upload_destination: '%kernel.project_dir%/public/pdf/upload/workshops'
            namer: vich_uploader.namer_uniqid
            inject_on_load: true
        users_images:
            uri_prefix: '%users_images_directory%'
            upload_destination: '%kernel.project_dir%/public/img/upload/users'
            namer: vich_uploader.namer_uniqid
            inject_on_load: true
            delete_on_update: true
            delete_on_remove: true
        wallpapers_images:
            uri_prefix: '%wallpapers_images_directory%'
            upload_destination: '%kernel.project_dir%/public/img/upload/wallpapers'
            namer: vich_uploader.namer_uniqid
            inject_on_load: true
        categories_images:
            uri_prefix: '%categories_images_directory%'
            upload_destination: '%kernel.project_dir%/public/img/upload/categories'
            namer: vich_uploader.namer_uniqid
            inject_on_load: true
